DROP TABLE IF EXISTS sync_log;
DROP TABLE IF EXISTS task_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS magic_links;
DROP TABLE IF EXISTS users;
