cmake_minimum_required(VERSION 3.28)

if(NOT DEFINED HCB_SOURCE_DIR)
  message(FATAL_ERROR "HCB_SOURCE_DIR is required")
endif()

file(GLOB hcb_workflow_paths "${HCB_SOURCE_DIR}/.github/workflows/*.yml")
if(hcb_workflow_paths STREQUAL "")
  message(FATAL_ERROR "GitHub Actions workflows are missing")
endif()

foreach(hcb_workflow_path IN LISTS hcb_workflow_paths)
  file(STRINGS "${hcb_workflow_path}" hcb_workflow_lines)
  set(hcb_job_env FALSE)
  set(hcb_line_number 0)
  foreach(hcb_workflow_line IN LISTS hcb_workflow_lines)
    math(EXPR hcb_line_number "${hcb_line_number} + 1")
    if(hcb_workflow_line MATCHES "^    env:[ \\t]*$")
      set(hcb_job_env TRUE)
      continue()
    endif()
    if(hcb_workflow_line MATCHES "^    [^ \\t#].*$")
      set(hcb_job_env FALSE)
    endif()
    if(hcb_job_env AND hcb_workflow_line MATCHES "runner\\.")
      message(FATAL_ERROR
        "${hcb_workflow_path}:${hcb_line_number} uses the runner context in job-level env")
    endif()
  endforeach()
endforeach()
