function(hcb_validate_windows_x64_architecture architecture pointer_size)
  if(NOT architecture STREQUAL "AMD64" AND NOT architecture STREQUAL "x86_64")
    message(FATAL_ERROR "Windows x64 packaging requires AMD64, got: ${architecture}")
  endif()
  if(NOT pointer_size EQUAL 8)
    message(FATAL_ERROR "Windows x64 packaging requires 64-bit pointers, got: ${pointer_size}")
  endif()
endfunction()

function(hcb_configure_windows_x64_package target)
  if(NOT WIN32)
    message(FATAL_ERROR "Windows x64 packaging is only supported on Windows hosts")
  endif()
  if(NOT TARGET ${target})
    message(FATAL_ERROR "Windows x64 package target does not exist: ${target}")
  endif()
  hcb_validate_windows_x64_architecture("${CMAKE_SYSTEM_PROCESSOR}" "${CMAKE_SIZEOF_VOID_P}")

  set_target_properties(${target} PROPERTIES OUTPUT_NAME hot-cross-buns)
  install(TARGETS ${target} RUNTIME DESTINATION bin)
  qt_generate_deploy_qml_app_script(
    TARGET ${target}
    OUTPUT_SCRIPT hcb_windows_x64_deploy_script
  )
  install(SCRIPT "${hcb_windows_x64_deploy_script}")

  set(CPACK_GENERATOR NSIS PARENT_SCOPE)
  set(CPACK_PACKAGE_FILE_NAME "Hot-Cross-Buns-${PROJECT_VERSION}-windows-x64" PARENT_SCOPE)
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "Hot Cross Buns" PARENT_SCOPE)
  set(CPACK_NSIS_INSTALL_ROOT "\$PROGRAMFILES64" PARENT_SCOPE)
  set(CPACK_NSIS_DISPLAY_NAME "Hot Cross Buns" PARENT_SCOPE)
  set(CPACK_NSIS_PACKAGE_NAME "Hot Cross Buns" PARENT_SCOPE)
  set(CPACK_NSIS_MUI_ICON "${PROJECT_SOURCE_DIR}/build/icon.ico" PARENT_SCOPE)
  set(CPACK_NSIS_MUI_UNIICON "${PROJECT_SOURCE_DIR}/build/icon.ico" PARENT_SCOPE)
  set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\hot-cross-buns.exe" PARENT_SCOPE)
  set(CPACK_NSIS_EXECUTABLES_DIRECTORY bin PARENT_SCOPE)
  set(CPACK_NSIS_MENU_LINKS "hot-cross-buns.exe" "Hot Cross Buns" PARENT_SCOPE)
  set(CPACK_NSIS_MUI_FINISHPAGE_RUN "bin\\hot-cross-buns.exe" PARENT_SCOPE)
  set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON PARENT_SCOPE)
  set(CPACK_NSIS_MANIFEST_DPI_AWARE ON PARENT_SCOPE)
  set(CPACK_NSIS_IGNORE_LICENSE_PAGE ON PARENT_SCOPE)
  set(CPACK_PACKAGE_CHECKSUM SHA256 PARENT_SCOPE)
endfunction()
